# .github/workflows/job_destroy.yaml
name: Destroy Resources

on:
    workflow_call:
        inputs:
            project:
                description: "Project name"
                required: true
                type: string
            env:
                description: "Environment"
                required: true
                type: string
            aws_region:
                description: "AWS region"
                type: string
                default: "ca-central-1"
        secrets:
            db_name:
                description: "Database name"
            db_username:
                description: "Database username"
            db_password:
                description: "Database password"
            db_app_pwd:
                description: "App user password"
            db_readonly_pwd:
                description: "Readonly user password"
            cf_api_token:
                description: "Cloudflare API token"
            cf_zone_id:
                description: "Cloudflare zone id"
            aws_tf_role_arn:
                description: "AWS role for tf"
            aws_backend_bucket:
                description: "AWS bucket for tf remote backend"

jobs:
    destroy:
        name: Destroy Resources
        runs-on: ubuntu-latest
        timeout-minutes: 30
        env:
            TF_VERSION: 1.14.0
            TF_DIR: aws/${{ inputs.env }}
            TF_PLUGIN_CACHE_DIR: /home/runner/.terraform.d/plugin-cache
            TF_VAR_aws_region: ${{ inputs.aws_region }}
            TF_VAR_env: ${{ inputs.env }}
            TF_VAR_db_name: ${{ secrets.db_name }}
            TF_VAR_db_username: ${{ secrets.db_username }}
            TF_VAR_db_password: ${{ secrets.db_password }}
            TF_VAR_db_app_pwd: ${{ secrets.db_app_pwd }}
            TF_VAR_db_readonly_pwd: ${{ secrets.db_readonly_pwd }}
            TF_VAR_cloudflare_api_token: ${{ secrets.cf_api_token }}
            TF_VAR_cloudflare_zone_id: ${{ secrets.cf_zone_id }}
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Terraform
              uses: hashicorp/setup-terraform@v3
              with:
                  terraform_version: ${{ env.TF_VERSION }}

            - name: Configure AWS credentials (OIDC)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  role-to-assume: ${{ secrets.AWS_TF_ROLE_ARN}}
                  aws-region: ${{ inputs.AWS_REGION }}

            - name: Configure Terraform plugin cache
              run: |
                  mkdir -pv ${{ env.TF_PLUGIN_CACHE_DIR }}
                  echo 'plugin_cache_dir = "${{ env.TF_PLUGIN_CACHE_DIR }}"' > ~/.terraformrc

            - name: Cache Terraform plugins
              uses: actions/cache@v4
              with:
                  path: ${{ env.TF_PLUGIN_CACHE_DIR }}
                  key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}-${{ inputs.env }}-${{ hashFiles('aws/.terraform.lock.hcl') }}

            - name: Terraform init - S3 backend
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform init -reconfigure -input=false \
                    -backend-config="bucket=${{ secrets.aws_backend_bucket }}" \
                    -backend-config="region=${{ inputs.env }}" \
                    -backend-config="key=${{ inputs.project }}/${{ inputs.env }}/terraform.tfstate" \
                    -backend-config="encrypt=true"

            - name: Terraform Validate
              working-directory: ${{ env.TF_DIR }}
              run: |
                  terraform fmt -check -recursive -no-color
                  terraform validate -no-color

            - name: Destroy - Terraform Plan
              working-directory: ${{ env.TF_DIR }}
              id: destroy-plan
              run: terraform plan -out=destroy-tfplan -input=false -no-color -destroy

            - name: Destroy - Show plan (JSON)
              working-directory: ${{ env.TF_DIR }}
              run: terraform show -json destroy-tfplan > destroy-tfplan.json

            - name: Destroy - Save plan artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: tfplan-bundle-destroy
                  path: |
                      ${{ env.TF_DIR }}/destroy-tfplan
                      ${{ env.TF_DIR }}/destroy-tfplan.json
                  retention-days: 3

            - name: Destroy - Terraform Apply
              working-directory: ${{ env.TF_DIR }}
              run: terraform apply -auto-approve -no-color destroy-tfplan
